FS-2328: Remove python axe accessibility tests
communitiesuk/funding-service-design-authenticator pull request #125
Opened 2023-02-22 10:24 UTC by tferns

### Change description

As part of [FS-2328](https://digital.dclg.gov.uk/jira/browse/FS-2328), some work has been done to get axe up, running and working optionally on the e2e test repository, this has the benefit of being able to analyse applications from a user point of view and not having to add tests specific to each individual python microservice.  The purpose of this pull request is to remove the old python axe accessibility tests, once the e2e axe analysis is up and working and a valid replacement.

- [x] Unit tests and other appropriate tests added or updated
- [] README and other documentation has been updated / added (if needed) (doing atm...)

I will squash and write a meaningful commit message when doing so.

2023-02-22 17:28 UTC, tferns commented
Removing the accessibility tests seems to break the other tests for some reason, probably some test pollution I'll look at.

2023-02-24 09:28 UTC, Adam-W1 requested changes
I think we can remove some of the dependencies that the accessibility tests were using such as 'json2html'

2023-02-24 09:29 UTC, tferns commented
> I think we can remove some of the dependencies that the accessibility tests were using such as 'json2html'

Good point, there might be axe related stuff in there too.  I'll remove them in a bit

2023-02-27 11:20 UTC, Adam-W1 approved these changes

2023-02-27 11:28 UTC, merged